# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: btc-db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  app:
    container_name: btc-app
    build: .
    command: uvicorn src.main:app --host 0.0.0.0
    environment:
      - ENV=DOCKER
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db