# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: btc-db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432